version: '3.7'

services:
  channeler-redis:
    container_name: channeler-redis
    image: redis:5.0.7-alpine
    ports:
      - 6380:6379

  channeler-database:
    container_name: channeler-database
    image: postgres:12.1-alpine
    ports:
      - 5433:5432
    restart: always
    volumes:
      - channeler-database:/var/lib/postgresql/data

  channeler-server:
    build:
      context: ./server
    command: daphne --bind 0.0.0.0 --port 8000 channeler.asgi:application
    container_name: channeler-server
    depends_on: 
      - channeler-redis
      - channeler-database
    env_file: 
      - ./server/.env
    ports:
      - 8001:8000
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

  channeler-worker:
    build:
      context: ./server
    command: python manage.py rqworker
    container_name: channeler-worker
    depends_on: 
      - channeler-redis
      - channeler-database
    env_file: 
      - ./server/.env

  # channeler-client-vue:
  #   build:
  #     context: ./client-vue
  #   command: npm run serve
  #   container_name: channeler-client-vue
  #   depends_on: 
  #     - channeler-server
  #   ports:
  #     - 3001:3000

  channeler-client-react:
    build:
      context: ./client-react
    command: npm start
    container_name: channeler-client-react
    depends_on:
      - channeler-server
    ports:
      - 3001:3000

  # channeler-client-angular:
  #   build:
  #     context: ./client-angular
  #   command: ng serve --host 0.0.0.0
  #   container_name: channeler-client-angular
  #   depends_on:
  #     - channeler-server
  #   environment:
  #     - CHROME_BIN=chromium-browser
  #   ports:
  #     - 4201:4200

  channeler-nginx:
    build:
      context: ./nginx
    container_name: channeler-nginx
    depends_on:
      - channeler-server
      # - channeler-client-vue
      - channeler-client-react
      # - channeler-client-angular
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  channeler-database:
  media:
  static:
